# Generated by Django 2.2.10 on 2020-06-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='articles',
            field=models.ManyToManyField(related_name='sections', through='articles.ArticleTheme', to='articles.Article'),
        ),
    ]
