# Generated by Django 2.2.10 on 2020-06-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200620_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='articles',
            field=models.ManyToManyField(related_name='themes', through='articles.ArticleTheme', to='articles.Article'),
        ),
    ]
