# Generated by Django 2.2.10 on 2020-06-20 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200620_1726'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Theme',
            new_name='Themes',
        ),
    ]
